name: PROMOTE
on:
  pull_request:
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: "owner:saagie-devtools"
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: extract variable
        id: extract_variable
        run: echo "::set-output name=pr_number::${{ github.event.pull_request.number }}";echo "::set-output name=repo::${{ github.event.pull_request.number }}"
      - uses: actions/checkout@v3
      - name: extract current version
        id: extract_pr_version
        run: echo "::set-output name=v::$(cat version.properties | grep 'semver' | sed -e 's/^version.semver=//')"
      - name: run gradle promote
        uses: docker://eclipse-temurin:17
        env:
          # no docker image should be pushed in this test repository
          DOCKER_USERNAME: UNSET
          DOCKER_PASSWORD: UNSET
        with:
          args: ./gradlew promote --stacktrace
      - name: Delete PreRelease
        id: delete_prerelease
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.repos.listReleases(context.repo);
            await Promise.allSettled(result.data
              .filter(release => release.tag_name == "${{ steps.extract_pr_version.outputs.v }}")
              .map(release =>
                  github.repos.deleteRelease({
                    owner:      context.repo.owner,
                    repo:       context.repo.repo,
                    release_id: release.id,
                  })
              )
            );
            try {
              const getRefParams = {
                owner: context.repo.owner,
                repo:  context.repo.repo,
                ref:   "tags/${{ steps.extract_pr_version.outputs.v }}",
              };
              const getRef = await github.git.getRef(getRefParams);
              github.git.deleteRef(getRefParams);
            } catch (e) {
              if (e.status != 404) {
                throw e;
              }
            }
      - name: Remove buildMeta version
        uses: docker://eclipse-temurin:17
        with:
          args: ./gradlew incrementBuildMeta -Dversion.buildmeta=
      - name: extract real version
        id: extract_version
        run: echo "::set-output name=v::$(cat version.properties | grep 'semver' | sed -e 's/^version.semver=//')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.v }}
          release_name: Release ${{ steps.extract_version.outputs.v }}
          draft: false
          prerelease: false
      - name: Upload Release technologies Asset ZIP
        id: upload-release-asset-technologies-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp-zip/technologies.zip
          asset_name: technologies.zip
          asset_content_type: application/zip
      - name: Upload Release technologies Asset JSON
        id: upload-release-asset-technologies-json
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp-zip/docker_listing.json
          asset_name: docker_listing.json
          asset_content_type: application/json
      - name: Upload Release technologies Asset TEXT-PLAIN
        id: upload-release-asset-technologies-textplain
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp-zip/docker_listing.txt
          asset_name: docker_listing.txt
          asset_content_type: text/plain
      - name: Upgrade version
        uses: docker://eclipse-temurin:17
        with:
          args: ./gradlew incrementMinor -Dversion.buildmeta=

      - name: Commit files
        run: git commit -am "[BOT] Set new version"
        env:
          GIT_AUTHOR_NAME: GitHub Action Bot
          GIT_AUTHOR_EMAIL: github-action@saagie.com
          GIT_COMMITTER_NAME: GitHub Action Bot
          GIT_COMMITTER_EMAIL: github-action@saagie.com
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
